### ISSUE TITLE
Not working with a Dockerfile

### ISSUE THREAD

**Issue by juanwolf** [jclegras/tinyca#1]
Hi,

Thanks a lot for this project, I've been using for years now and my life would be way worst without it. However, today I tried to deploy it on ECS and I can't get the API responding to any of my calls.

Here's the dockerfile:

```
FROM golang:alpine AS builder
RUN apk update && apk add --no-cache git
WORKDIR $GOPATH/src/github.com/jclegras/tinyca/
COPY . .
RUN go get -d -v
RUN go build -o /go/bin/tinyca


FROM alpine:latest
COPY --from=builder /go/bin/tinyca /go/bin/tinyca
EXPOSE 8080
ENTRYPOINT ["/go/bin/tinyca"]
```

Nothing appears to the log and I don't understand why. Let me know if I can help! Thanks!!!

**Comment by jclegras** [comment]
Hi @juanwolf, thanks a lot for your feedback.

Currently, tinyca does not support container based deployment.
This will be looked at in the future but feel free to contribute if you have the time.

**UPDATE** Docker support added here : https://github.com/jclegras/tinyca/commit/84dd65f5c10f7eec063aacf3e6c4a137473ea4e1
